name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hetzner
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            if [ ! -d /var/www/todo ]; then
              sudo mkdir -p /var/www/todo
              sudo chown -R $USER:$USER /var/www/todo
              cd /var/www/todo
              sudo git clone https://github.com/Mee1ad/to-do.git .
            else
              cd /var/www/todo
              if [ -d .git ]; then
                sudo git pull origin main
              else
                sudo git clone https://github.com/Mee1ad/to-do.git .
              fi
            fi
            if [ -f docker-compose.yml ]; then
              sudo docker compose restart web
            else
              echo "Error: docker-compose.yml not found!"
              exit 1
            fi
          EOF
